language: nodejs
cache: yarn
install:
  - yarn install
jobs:
  include:
    - stage: lint, test and build
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: release
      script: yarn build:production
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          branch: master
          tags: true
          repo: AJStacy/Adze
        skip_cleanup: 'true'
