language: nodejs
cache: yarn
install:
  - yarn install
jobs:
  include:
    - stage: lint, test and build
      script:
        - yarn lint
        - yarn test
        - yarn build
    - stage: release
      script: yarn build:production
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        skip_cleanup: true
        keep_history: true
        on:
          branch: master
          tags: true
          repo: AJStacy/Adze

    - stage: docs
      cache:
        directories: node_modules
      script: yarn docs:build
      script: ls .
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs/.vuepress/dist
        github_token: $GITHUB_TOKEN # A token generated on GitHub allowing Travis to push code on you repository. Set in the Travis settings page of your repository, as a secure variable
        repo: AJStacy/Adze
        keep_history: true
        on:
          branch: master
