name: Docs Only
on:
  push:
    branches: [master]

jobs:
  docs:
    runs-on: ubuntu-latest
    if: startsWith(github.event.head_commit.message, 'docs:')
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Build Content
        run: yarn docs:build
      - name: Publish
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.1
        with:
          dir: docs/.vuepress/dist
          branch: gh-pages
          token: ${{ secrets.PAGES_TOKEN }}
