name: Validation
on: [ push ]

jobs:
  lint:
    name: Lint
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
  test:
    name: Test
    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - uses: bahmutov/npm-install@v1
      - run: yarn test
  build:
    name: Build
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        uses: bahmutov/npm-install@v1
      - run: yarn build